name: Suggest Documentation Update

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  suggest-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Python Dependencies
        run: |
          pip install google-generativeai

      - name: Configure Git
        run: |
          git config --global user.email "docbot@example.com"
          git config --global user.name "Doc Bot"

      - name: Set up GitHub CLI
        run: |
          sudo apt-get install gh

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${GH_TOKEN}" | gh auth login --with-token

      - name: Run Documentation Suggester
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          DOCS_REPO_URL: ${{ secrets.DOCS_REPO_URL }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/suggest_docs.py
